Loading the necessary packages

In [1]:
import pandas as pd
import sklearn # scikit learn package will be very helpful
import numpy as np

from sklearn.neighbors import NearestNeighbors  # for finding nearest neighbors between two data sets

Reading in the data sets

In [2]:
# reading in the first pancreas data set

pancreas_data = pd.read_table("GSE81076_D2_3_7_10_17.txt")  
pancreas_data

,Unnamed: 0,D2ex_1,D2ex_2,D2ex_3,D2ex_4,D2ex_5,D2ex_6,D2ex_7,D2ex_8,D2ex_9,...,D17TGFB_87,D17TGFB_88,D17TGFB_89,D17TGFB_90,D17TGFB_91,D17TGFB_92,D17TGFB_93,D17TGFB_94,D17TGFB_95,D17TGFB_96
0,A1BG-AS1__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,A1BG__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.001958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,A1CF__chr10,0.000000,2.007853,1.001958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.001958,0.000000,0.000000,1.001958,1.001958,1.001958,1.001958,0.000000,0.0
3,A2M-AS1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,A2ML1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.007853,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20143,ZYG11A__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
20144,ZYG11B__chr1,0.000000,1.001958,0.000000,5.049473,1.001958,1.001958,1.001958,1.001958,0.000000,...,1.001958,1.001958,2.007853,0.000000,0.000000,1.001958,1.001958,1.001958,1.001958,0.0
20145,ZYX__chr7,1.001958,0.000000,3.017717,2.007853,0.000000,4.031579,0.000000,1.001958,2.007853,...,7.097484,4.031579,0.000000,1.001958,1.001958,0.000000,0.000000,0.000000,1.001958,0.0
20146,ZZEF1__chr17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.001958,0.000000,...,0.000000,0.000000,1.001958,0.000000,0.000000,1.001958,0.000000,0.000000,0.000000,0.0
20147,ZZZ3__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.001958,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [3]:
# reading in the second pancreas data set - gene names are already the row names here

pancreas_data_2 = pd.read_table("GSE85241_cellsystems_dataset_4donors_updated.csv")  
pancreas_data_2

,D28-1_1,D28-1_2,D28-1_3,D28-1_4,D28-1_5,D28-1_6,D28-1_7,D28-1_8,D28-1_9,D28-1_10,...,D30-8_87,D30-8_88,D30-8_89,D30-8_90,D30-8_91,D30-8_92,D30-8_93,D30-8_94,D30-8_95,D30-8_96
A1BG-AS1__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
A1BG__chr19,0.000000,0.000000,1.001958,1.001958,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.007853,0.0,0.0
A1CF__chr10,6.071431,0.000000,2.007853,6.071431,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,1.001958,7.097484,3.017717,0.000000,3.017717,0.000000,0.000000,0.0,0.0
A2M-AS1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,2.007853,0.000000,1.001958,0.000000,0.000000,0.000000,0.0,0.0
A2ML1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A__chr1,0.000000,0.000000,0.000000,1.001958,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ZYG11B__chr1,2.007853,6.071431,1.001958,6.071431,3.017717,0.0,0.0,0.0,0.0,0.0,...,9.162012,2.007853,2.007853,1.001958,4.031579,2.007853,3.017717,9.162012,0.0,0.0
ZYX__chr7,0.000000,5.049473,0.000000,1.001958,0.000000,0.0,0.0,0.0,0.0,0.0,...,3.017717,0.000000,0.000000,0.000000,0.000000,1.001958,8.127667,5.049473,0.0,0.0
ZZEF1__chr17,0.000000,4.031579,1.001958,3.017717,0.000000,0.0,0.0,0.0,0.0,0.0,...,2.007853,0.000000,1.001958,0.000000,4.031579,0.000000,2.007853,3.017717,0.0,0.0
ZZZ3__chr1,0.000000,1.001958,0.000000,2.007853,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,4.031579,0.000000,4.031579,1.001958,0.000000,0.000000,0.0,0.0

Modifying the data sets to the needed formats

In [4]:
# setting the gene names as the row names

pancreas_data = pancreas_data.rename(columns = {"Unnamed: 0":"Genes"}) 
pancreas_data.set_index(["Genes"], inplace = True)
pancreas_data

,D2ex_1,D2ex_2,D2ex_3,D2ex_4,D2ex_5,D2ex_6,D2ex_7,D2ex_8,D2ex_9,D2ex_10,...,D17TGFB_87,D17TGFB_88,D17TGFB_89,D17TGFB_90,D17TGFB_91,D17TGFB_92,D17TGFB_93,D17TGFB_94,D17TGFB_95,D17TGFB_96
Genes,,,,,,,,,,,,,,,,,,,,,
A1BG-AS1__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
A1BG__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,1.001958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
A1CF__chr10,0.000000,2.007853,1.001958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,1.001958,0.000000,0.000000,1.001958,1.001958,1.001958,1.001958,0.000000,0.0
A2M-AS1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
A2ML1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.007853,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
ZYG11B__chr1,0.000000,1.001958,0.000000,5.049473,1.001958,1.001958,1.001958,1.001958,0.000000,0.0,...,1.001958,1.001958,2.007853,0.000000,0.000000,1.001958,1.001958,1.001958,1.001958,0.0
ZYX__chr7,1.001958,0.000000,3.017717,2.007853,0.000000,4.031579,0.000000,1.001958,2.007853,0.0,...,7.097484,4.031579,0.000000,1.001958,1.001958,0.000000,0.000000,0.000000,1.001958,0.0
ZZEF1__chr17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.001958,0.000000,0.0,...,0.000000,0.000000,1.001958,0.000000,0.000000,1.001958,0.000000,0.000000,0.000000,0.0
ZZZ3__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.001958,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

Cosine normalization

In [5]:
# for cosine normalization

from sklearn.preprocessing import Normalizer

In [6]:
# cosine normalization of first pancreas data set - gets rid of row names and column names though...

transformer = Normalizer().fit(pancreas_data)
pancreas_data_cnorm = pd.DataFrame(transformer.transform(pancreas_data))
pancreas_data_cnorm

,0,1,2,3,4,5,6,7,8,9,...,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.033422,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,0.000000,0.066485,0.033177,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.033177,0.000000,0.000000,0.033177,0.033177,0.033177,0.033177,0.000000,0.0
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.121129,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
20144,0.000000,0.007053,0.000000,0.035542,0.007053,0.007053,0.007053,0.007053,0.000000,0.0,...,0.007053,0.007053,0.014133,0.000000,0.000000,0.007053,0.007053,0.007053,0.007053,0.0
20145,0.013294,0.000000,0.040040,0.026641,0.000000,0.053492,0.000000,0.013294,0.026641,0.0,...,0.094171,0.053492,0.000000,0.013294,0.013294,0.000000,0.000000,0.000000,0.013294,0.0
20146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.042107,0.000000,0.0,...,0.000000,0.000000,0.042107,0.000000,0.000000,0.042107,0.000000,0.000000,0.000000,0.0
20147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.061075,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [7]:
# function adapted from HW1 - cosine normalization 

def normalizing_cells_MaxAbsScaler(data):
    
    """
        input data: data frame with gene expression data  
            columns are the cells and rows are genes
        output data_normalized_data_values: normalized (scaled) data
        function:  dividing the value of each gene for each cell 
                by the maximum value of that cell.
    """
    import sklearn.preprocessing
    
    # creating the list of patients
    cells = data.columns.values
    
    #using Sklearn to scale the data 
    scaler = sklearn.preprocessing.MaxAbsScaler()
    data_scaled = scaler.fit_transform(data)
    
    #creating the dataframe, the output of sklearn MaxAbsScaler is an array
    data_normalized_data_values = pd.DataFrame(data_scaled, columns= cells, index = data.index)
      
    return data_normalized_data_values

In [8]:
# cosine normalization here keeps the gene and cell names in the rows and columns, respectively
# cosine normalization for the first pancreas data set

normalized_pancreas = normalizing_cells_MaxAbsScaler(pancreas_data)
normalized_pancreas

,D2ex_1,D2ex_2,D2ex_3,D2ex_4,D2ex_5,D2ex_6,D2ex_7,D2ex_8,D2ex_9,D2ex_10,...,D17TGFB_87,D17TGFB_88,D17TGFB_89,D17TGFB_90,D17TGFB_91,D17TGFB_92,D17TGFB_93,D17TGFB_94,D17TGFB_95,D17TGFB_96
Genes,,,,,,,,,,,,,,,,,,,,,
A1BG-AS1__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.0
A1BG__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.005776,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.0
A1CF__chr10,0.000000,0.001993,0.000941,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.005776,0.000000,0.000000,0.00088,0.00088,0.000627,0.001313,0.000000,0.0
A2M-AS1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.0
A2ML1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.002632,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.0
ZYG11B__chr1,0.000000,0.000994,0.000000,0.038319,0.012049,0.007604,0.008911,0.01077,0.00000,0.0,...,0.005340,0.005776,0.001257,0.000000,0.00000,0.00088,0.000627,0.001313,0.000941,0.0
ZYX__chr7,0.003588,0.000000,0.002834,0.015237,0.000000,0.030595,0.000000,0.01077,0.01070,0.0,...,0.037824,0.023240,0.000000,0.001595,0.00088,0.00000,0.000000,0.000000,0.000941,0.0
ZZEF1__chr17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.01077,0.00000,0.0,...,0.000000,0.000000,0.000627,0.000000,0.00000,0.00088,0.000000,0.000000,0.000000,0.0
ZZZ3__chr1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00534,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.0

In [9]:
# cosine normalization here keeps the gene and cell names in the rows and columns, respectively
# cosine normalization for the second pancreas data set

normalized_pancreas_2 = normalizing_cells_MaxAbsScaler(pancreas_data_2)
normalized_pancreas_2

,D28-1_1,D28-1_2,D28-1_3,D28-1_4,D28-1_5,D28-1_6,D28-1_7,D28-1_8,D28-1_9,D28-1_10,...,D30-8_87,D30-8_88,D30-8_89,D30-8_90,D30-8_91,D30-8_92,D30-8_93,D30-8_94,D30-8_95,D30-8_96
A1BG-AS1__chr19,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
A1BG__chr19,0.000000,0.000000,0.000627,0.001043,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002492,0.0,0.0
A1CF__chr10,0.003802,0.000000,0.001257,0.006319,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000627,0.004444,0.002429,0.000000,0.001890,0.000000,0.000000,0.0,0.0
A2M-AS1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.001257,0.000000,0.001505,0.000000,0.000000,0.000000,0.0,0.0
A2ML1__chr12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A__chr1,0.000000,0.000000,0.000000,0.001043,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ZYG11B__chr1,0.001257,0.007314,0.000627,0.006319,0.011157,0.0,0.0,0.0,0.0,0.0,...,0.016433,0.001257,0.001257,0.000807,0.006055,0.001257,0.005413,0.011371,0.0,0.0
ZYX__chr7,0.000000,0.006083,0.000000,0.001043,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.005413,0.000000,0.000000,0.000000,0.000000,0.000627,0.014578,0.006267,0.0,0.0
ZZEF1__chr17,0.000000,0.004857,0.000627,0.003141,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.003601,0.000000,0.000627,0.000000,0.006055,0.000000,0.003601,0.003745,0.0,0.0
ZZZ3__chr1,0.000000,0.001207,0.000000,0.002090,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.002524,0.000000,0.006055,0.000627,0.000000,0.000000,0.0,0.0

Transposing the two data sets - want the cells in the rows now and the genes in the columns

In [10]:
# transposing the first data set

normalized_pancreas_t = normalized_pancreas.transpose()

In [11]:
# transposing the second data set

normalized_pancreas_2_t = normalized_pancreas_2.transpose()

Dropping any missing values from the transposed data sets

In [12]:
# dropping missing values in the first pancreas data set - looks like there aren't any here

normalized_pancreas_t.dropna(axis=1) 
normalized_pancreas_t

Genes,A1BG-AS1__chr19,A1BG__chr19,A1CF__chr10,A2M-AS1__chr12,A2ML1__chr12,A2MP1__chr12,A2M__chr12,A4GALT__chr22,A4GNT__chr3,AAAS__chr12,...,ZWILCH__chr15,ZWINT__chr10,ZXDA__chrX,ZXDB__chrX,ZXDC__chr3,ZYG11A__chr1,ZYG11B__chr1,ZYX__chr7,ZZEF1__chr17,ZZZ3__chr1
D2ex_1,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.003588,0.00000,0.0
D2ex_2,0.0,0.0,0.001993,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000994,0.0,0.000994,0.000000,0.00000,0.0
D2ex_3,0.0,0.0,0.000941,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000941,0.0,0.000000,0.002834,0.00000,0.0
D2ex_4,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.007604,0.007604,0.0,0.038319,0.015237,0.00000,0.0
D2ex_5,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.012049,0.0,0.012049,0.000000,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D17TGFB_92,0.0,0.0,0.000880,0.0,0.000000,0.0,0.0,0.0,0.0,0.000880,...,0.0,0.0,0.0,0.000000,0.000880,0.0,0.000880,0.000000,0.00088,0.0
D17TGFB_93,0.0,0.0,0.000627,0.0,0.000000,0.0,0.0,0.0,0.0,0.000627,...,0.0,0.0,0.0,0.000000,0.000627,0.0,0.000627,0.000000,0.00000,0.0
D17TGFB_94,0.0,0.0,0.001313,0.0,0.002632,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.001313,0.0,0.001313,0.000000,0.00000,0.0
D17TGFB_95,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000941,...,0.0,0.0,0.0,0.000000,0.000941,0.0,0.000941,0.000941,0.00000,0.0
D17TGFB_96,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.332025,0.0,0.000000,0.000000,0.00000,0.0

In [13]:
# verifying that there are no missing values in the first pancreas data set

normalized_pancreas_t.isnull().values.any()

False

In [14]:
# dropping missing values in the second pancreas data set - looks like there aren't any here

normalized_pancreas_2_t.dropna(axis=1) 
normalized_pancreas_2_t

,A1BG-AS1__chr19,A1BG__chr19,A1CF__chr10,A2M-AS1__chr12,A2ML1__chr12,A2M__chr12,A4GALT__chr22,A4GNT__chr3,AAAS__chr12,AACSP1__chr5,...,ZWILCH__chr15,ZWINT__chr10,ZXDA__chrX,ZXDB__chrX,ZXDC__chr3,ZYG11A__chr1,ZYG11B__chr1,ZYX__chr7,ZZEF1__chr17,ZZZ3__chr1
D28-1_1,0.0,0.000000,0.003802,0.0,0.0,0.000000,0.000000,0.0,0.000627,0.0,...,0.000000,0.0,0.000000,0.000627,0.003162,0.000000,0.001257,0.000000,0.000000,0.000000
D28-1_2,0.0,0.000000,0.000000,0.0,0.0,0.006083,0.001207,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.001207,0.011037,0.000000,0.007314,0.006083,0.004857,0.001207
D28-1_3,0.0,0.000627,0.001257,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000627,0.000000,0.000627,0.000000,0.000627,0.000000,0.000627,0.000000
D28-1_4,0.0,0.001043,0.006319,0.0,0.0,0.000000,0.000000,0.0,0.001043,0.0,...,0.000000,0.0,0.000000,0.002090,0.010616,0.001043,0.006319,0.001043,0.003141,0.002090
D28-1_5,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.011157,0.000000,0.011157,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D30-8_92,0.0,0.000000,0.001890,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000627,0.000627,0.004444,0.000000,0.001257,0.000627,0.000000,0.000627
D30-8_93,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.001797,0.0,...,0.000000,0.0,0.000000,0.000000,0.001797,0.000000,0.005413,0.014578,0.003601,0.000000
D30-8_94,0.0,0.002492,0.000000,0.0,0.0,0.008809,0.001244,0.0,0.001244,0.0,...,0.001244,0.0,0.000000,0.002492,0.010088,0.000000,0.011371,0.006267,0.003745,0.000000
D30-8_95,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D30-8_96,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.008110,0.000000,0.000000,0.000000,0.000000,0.000000

In [15]:
# verifying that there are no missing values in the second pancreas data set

normalized_pancreas_2_t.isnull().values.any()

False

Subsetting the 2 data sets based on the common genes whose expression was measured in both data sets

In [16]:
# finding the common genes (aka. features) that were measured in the two data sets

common_cols = list(set.intersection(set(normalized_pancreas_t.columns), set(normalized_pancreas_2_t.columns)))
common_cols = [col for col in set(normalized_pancreas_t.columns).intersection(normalized_pancreas_2_t.columns)]

In [17]:
# adjusting the transposed versions of the two original data sets to only have the common genes or features

normalized_pancreas_t_adj = normalized_pancreas_t[common_cols]
normalized_pancreas_2_t_adj = normalized_pancreas_2_t[common_cols]

In [18]:
# Viewing the first data set up to this point (cells are now in the rows, genes are now in the columns)

normalized_pancreas_t_adj

Genes,ACER3__chr11,HAUS6__chr9,IMMP1L__chr11,RHOXF1__chrX,UHRF1BP1L__chr12,FAM65A__chr16,RPS23__chr5,ASXL2__chr2,ERCC-00120,SCUBE3__chr6,...,WISP1__chr8,ALK__chr2,SLC24A1__chr15,MGP__chr12,SLC24A6__chr12,ASPSCR1__chr17,CLCN6__chr1,OSGIN1__chr16,DNAJC9__chr10,CCL26__chr7
D2ex_1,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.090243,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.003588,0.0
D2ex_2,0.0,0.000000,0.000994,0.0,0.0,0.000994,0.012198,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000994,0.0,0.000000,0.000000,0.0
D2ex_3,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.016522,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0
D2ex_4,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.174567,0.007604,0.0,0.0,...,0.0,0.0,0.0,0.0,0.015237,0.000000,0.0,0.000000,0.000000,0.0
D2ex_5,0.0,0.000000,0.000000,0.0,0.0,0.012049,0.135210,0.012049,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.012049,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D17TGFB_92,0.0,0.000000,0.000000,0.0,0.0,0.001764,0.014514,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000880,0.0
D17TGFB_93,0.0,0.000000,0.001257,0.0,0.0,0.000000,0.027235,0.000627,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0
D17TGFB_94,0.0,0.001313,0.000000,0.0,0.0,0.000000,0.017487,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0
D17TGFB_95,0.0,0.000000,0.000941,0.0,0.0,0.000000,0.007634,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000941,0.0,0.000000,0.000000,0.0
D17TGFB_96,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0

In [19]:
# Viewing the second data set up to this point (cells are now in the rows, genes are now in the columns)

normalized_pancreas_2_t_adj

,ACER3__chr11,HAUS6__chr9,IMMP1L__chr11,RHOXF1__chrX,UHRF1BP1L__chr12,FAM65A__chr16,RPS23__chr5,ASXL2__chr2,ERCC-00120,SCUBE3__chr6,...,WISP1__chr8,ALK__chr2,SLC24A1__chr15,MGP__chr12,SLC24A6__chr12,ASPSCR1__chr17,CLCN6__chr1,OSGIN1__chr16,DNAJC9__chr10,CCL26__chr7
D28-1_1,0.000627,0.000627,0.000627,0.0,0.000000,0.000000,0.015090,0.000627,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000627,0.0
D28-1_2,0.004857,0.000000,0.001207,0.0,0.000000,0.003635,0.041180,0.001207,0.0,0.0,...,0.000000,0.0,0.000000,0.001207,0.000000,0.0,0.002419,0.000000,0.000000,0.0
D28-1_3,0.000000,0.000000,0.000000,0.0,0.000000,0.000627,0.015090,0.001257,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000627,0.000000,0.000000,0.0
D28-1_4,0.001043,0.002090,0.003141,0.0,0.000000,0.002090,0.055320,0.001043,0.0,0.0,...,0.000000,0.0,0.001043,0.000000,0.000000,0.0,0.000000,0.000000,0.001043,0.0
D28-1_5,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.018669,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.003704,0.0,0.000000,0.003704,0.003704,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D30-8_92,0.000000,0.000000,0.000627,0.0,0.000000,0.000627,0.025024,0.000627,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000627,0.000000,0.000000,0.0
D30-8_93,0.000000,0.000000,0.000000,0.0,0.001797,0.001797,0.057231,0.000000,0.0,0.0,...,0.001797,0.0,0.001797,0.001797,0.001797,0.0,0.000000,0.000000,0.001797,0.0
D30-8_94,0.000000,0.003745,0.000000,0.0,0.001244,0.007536,0.093066,0.005004,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.001244,0.0,0.000000,0.000000,0.001244,0.0
D30-8_95,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
D30-8_96,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0

Performing the Nearest Neighbors Algorithm

In [20]:
# Finding the nearest neighbors of cells from batch 2 to cells in batch 1 and saving the indices of the nearest neighbors in batch 1

NN1 = NearestNeighbors(n_neighbors = 20, algorithm = "kd_tree").fit(normalized_pancreas_t_adj)
dist1, indices1 = NN1.kneighbors(normalized_pancreas_2_t_adj)
indices1

array([[1447, 1683, 1381, ..., 1449, 1380, 1386],
       [1382,  853, 1477, ..., 1448, 1258, 1362],
       [1478, 1068, 1472, ..., 1212, 1647,  842],
       ...,
       [1287, 1281, 1298, ..., 1484, 1382, 1477],
       [ 767, 1116, 1078, ...,  943, 1122,  438],
       [ 767, 1116, 1149, ..., 1228,  177, 1183]])

In [21]:
# looking at the shape of the array of saved indices from above
# 3072 cells from the second pancreas data set, and finding 20 nearest neighbors --> the dimensions make sense

indices1.shape

(3072, 20)

In [22]:
# Finding the nearest neighbors of cells from batch 1 to cells in batch 2 and saving the indices of the nearest neighbors in batch 2

NN2 = NearestNeighbors(n_neighbors = 20, algorithm = "kd_tree").fit(normalized_pancreas_2_t_adj)
dist2, indices2 = NN2.kneighbors(normalized_pancreas_t_adj)
indices2

array([[2773,  965, 2400, ...,  994,  144, 2497],
       [2823, 2322, 2394, ..., 1920, 2609, 1780],
       [3011,  266, 1562, ..., 1914, 2090, 1706],
       ...,
       [3054, 2152,  813, ..., 2376, 1850, 1559],
       [2700, 2098,  990, ..., 1515, 1298, 1944],
       [1979, 1923, 2039, ..., 1767, 1914, 3011]])

In [23]:
# looking at the shape of the array of saved indices from above
# 1728 cells from the first pancreas data set, and finding 20 nearest neighbors --> the dimensions make sense

indices2.shape

(1728, 20)

In [24]:
# array of 0's and 1's, with 1's indicating a k-nearest neighbor of a cell in batch 2

graph1 = NN1.kneighbors_graph(normalized_pancreas_2_t_adj).toarray()
graph1

# rows in the matrix output below are the indices of cells in data set 2, columns in the matrix output below are
# indices of cells in data set 1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
# looking at the shape of the array from above

graph1.shape

(3072, 1728)

In [26]:
# array of 0's and 1's, with 1's indicating a k-nearest neighbor of a cell in batch 1

graph2 = NN2.kneighbors_graph(normalized_pancreas_t_adj).toarray()
graph2

# rows in the matrix output below are the indices of cells in data set 1, columns in the matrix output below are
# indices of cells in data set 2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
# looking at the shape of the array from above

graph2.shape

(1728, 3072)

In [28]:
# transposing one of the arrays of 0's and 1's to allow for element-wise multiplication in the next step

data1T = np.transpose(graph1)

#data2T = np.transpose(graph2)

In [29]:
# element-wise multiplication of the two arrays of 0's and 1's

W = np.multiply(data1T,graph2)

In [30]:
# MNN pairs of indices, with the first index in each pair indicating the index of the cell in the first pancreas data
# set and the second index in each pair indicating the index of the cell in the second pancreas data set

Windices = (W>0).nonzero()

In [31]:
# first array in tuple holds the indices of cells in batch 1 in the MNN pairs
# second array in tuple holds the indices of cells in batch 2 in the MNN pairs

Windices

(array([   0,    1,    1, ..., 1724, 1724, 1724]),
 array([2773,  256,  276, ..., 1229, 1976, 2672]))

In [32]:
# batch correction vectors for MNN pairs

correction_vectors = {}
for key in range(0,len(indices2)):
    #breakpoint()
    correction_vectors[key] = {}
    dist = list(dist2[key])
    indices = list(indices2[key])
    for i in range(0,len(dist)):
        correction_vectors[key][indices[i]] = dist[i]

In [33]:
# saving the distances of the MNN pairs in a list

distances = []

for i in range(0,len(Windices[0])):
    one = Windices[0][i]
    two = Windices[1][i]
    distances.append(correction_vectors[one][two])

In [ ]:
# Gaussian kernel 
# adapted from https://stats.stackexchange.com/questions/15798/how-to-calculate-a-gaussian-kernel-effectively-in-numpy

def my_kernel(X,Y):
    K = np.zeros((X.shape[0],Y.shape[0]))
    for i,x in enumerate(X):
        for j,y in enumerate(Y):
            K[i,j] = np.exp(-1*np.linalg.norm(x-y)**2)
    return K